"""empty message

Revision ID: 56bc8176a06b
Revises: cdc381f837fb
Create Date: 2024-04-17 20:40:15.243573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56bc8176a06b'
down_revision = 'cdc381f837fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_home_new_product',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键'),
    sa.Column('product_id', sa.BigInteger(), nullable=True, comment='商品ID'),
    sa.Column('product_name', sa.String(length=128), nullable=True, comment='商品标题'),
    sa.Column('recommend_status', sa.Integer(), nullable=True, comment='推荐状态:0-未推荐;1-推荐'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('gmt_create', sa.BigInteger(), nullable=False, comment='创建时间'),
    sa.Column('gmt_modified', sa.BigInteger(), nullable=False, comment='更新时间'),
    sa.Column('create_uid', sa.String(length=64), nullable=False, comment='创建人uid'),
    sa.Column('create_uname', sa.String(length=64), nullable=False, comment='创建人昵称'),
    sa.Column('modified_uid', sa.String(length=64), nullable=False, comment='更新人uid'),
    sa.Column('modified_uname', sa.String(length=64), nullable=False, comment='更新人昵称'),
    sa.Column('enable', sa.SmallInteger(), nullable=False, comment='是否删除:0-未删除;1-删除'),
    sa.Column('merchant_id', sa.String(length=32), nullable=True, comment='商户ID'),
    sa.PrimaryKeyConstraint('id'),
    comment='新品推荐表'
    )
    op.create_table('t_product',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='商品主键ID'),
    sa.Column('product_no', sa.String(length=60), nullable=True, comment='商品编号'),
    sa.Column('product_name', sa.String(length=255), nullable=True, comment='商品名称'),
    sa.Column('rel_tenant_id', sa.BigInteger(), nullable=True, comment='商户id'),
    sa.Column('rel_default_sku_id', sa.BigInteger(), nullable=True, comment='默认SKU'),
    sa.Column('rel_category1_id', sa.BigInteger(), nullable=True, comment='一级类目'),
    sa.Column('rel_category2_id', sa.BigInteger(), nullable=True, comment='二级类目'),
    sa.Column('rel_category3_id', sa.BigInteger(), nullable=True, comment='三级类目'),
    sa.Column('spec_options', sa.String(length=60), nullable=True, comment='规格选项id集合'),
    sa.Column('price', sa.Numeric(precision=11, scale=2), nullable=True, comment='商城价'),
    sa.Column('default_pic', sa.String(length=512), nullable=True, comment='商品图片'),
    sa.Column('album_pics', sa.Text(), nullable=True, comment='商品组图,加上默认主图，最多允许5张图，逗号分割'),
    sa.Column('sales_num', sa.Integer(), nullable=True, comment='销量'),
    sa.Column('detail_desc', sa.String(length=512), nullable=True, comment='商品详情描述'),
    sa.Column('publish_status', sa.SmallInteger(), nullable=True, comment='上架状态：0->下架；1->上架'),
    sa.Column('detail_html', sa.String(length=512), nullable=True, comment='商品详情web端页面，基本以图为主，富文本HTML样式'),
    sa.Column('enabled', sa.SmallInteger(), nullable=False, comment='逻辑删除 0-未删除，1-删除'),
    sa.Column('gmt_create', sa.BigInteger(), nullable=True, comment='创建时间'),
    sa.Column('gmt_modified', sa.BigInteger(), nullable=True, comment='更新时间'),
    sa.Column('modified_uid', sa.String(length=50), nullable=True, comment='更新人uid'),
    sa.Column('create_uid', sa.String(length=50), nullable=True, comment='创建人uid'),
    sa.Column('create_uname', sa.String(length=255), nullable=True, comment='创建人昵称'),
    sa.Column('modified_uname', sa.String(length=255), nullable=True, comment='更新人昵称'),
    sa.PrimaryKeyConstraint('id'),
    comment='商品表'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_product')
    op.drop_table('t_home_new_product')
    # ### end Alembic commands ###
