"""empty message

Revision ID: d458caf58f8f
Revises: d5f7d2b954b9
Create Date: 2024-04-20 19:41:32.251522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd458caf58f8f'
down_revision = 'd5f7d2b954b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_product_full_reduction',
    sa.Column('id', sa.BIGINT(), nullable=False, comment='主键id'),
    sa.Column('product_id', sa.BIGINT(), nullable=True, comment='商品id'),
    sa.Column('full_price', sa.Float(precision=10, asdecimal=2), nullable=True, comment='商品满足金额'),
    sa.Column('reduce_price', sa.Float(precision=10, asdecimal=2), nullable=True, comment='商品减少金额'),
    sa.Column('start_time', sa.BIGINT(), nullable=True, comment='开始时间'),
    sa.Column('end_time', sa.BIGINT(), nullable=True, comment='结束时间'),
    sa.Column('gmt_create', sa.BIGINT(), nullable=True, comment='创建时间'),
    sa.Column('create_uid', sa.String(length=50), nullable=True, comment='创建人id'),
    sa.Column('create_uname', sa.String(length=255), nullable=True, comment='创建人昵称'),
    sa.Column('gmt_modified', sa.BIGINT(), nullable=True, comment='更新时间'),
    sa.Column('modified_uid', sa.String(length=50), nullable=True, comment='更新人id'),
    sa.Column('modified_uname', sa.String(length=255), nullable=True, comment='更新人昵称'),
    sa.PrimaryKeyConstraint('id'),
    comment='商品满减表'
    )
    op.create_table('t_spec_type',
    sa.Column('id', sa.BIGINT(), nullable=False, comment='规格类别id'),
    sa.Column('name', sa.String(length=50), nullable=True, comment='规格类别名称'),
    sa.Column('gmt_create', sa.BIGINT(), nullable=True, comment='创建时间'),
    sa.Column('gmt_modified', sa.BIGINT(), nullable=True, comment='更新时间'),
    sa.Column('enabled', sa.Integer(), nullable=True, comment='逻辑删除 0-未删除，1-删除'),
    sa.Column('modified_uid', sa.String(length=50), nullable=True, comment='更新人uid'),
    sa.Column('create_uid', sa.String(length=50), nullable=True, comment='创建人uid'),
    sa.Column('modified_uname', sa.String(length=255), nullable=True, comment='更新人昵称'),
    sa.Column('create_uname', sa.String(length=255), nullable=True, comment='创建人昵称'),
    sa.PrimaryKeyConstraint('id'),
    comment='商品规格类型表'
    )
    op.create_table('t_specification',
    sa.Column('id', sa.BIGINT(), nullable=False, comment='规格主键'),
    sa.Column('name', sa.String(length=50), nullable=True, comment='规格名称'),
    sa.Column('rel_category_id', sa.BIGINT(), nullable=True, comment='类目id'),
    sa.Column('rel_spec_type_id', sa.BIGINT(), nullable=True, comment='规格分类id'),
    sa.Column('gmt_create', sa.BIGINT(), nullable=True, comment='创建时间'),
    sa.Column('gmt_modified', sa.BIGINT(), nullable=True, comment='更新时间'),
    sa.Column('enabled', sa.Integer(), nullable=True, comment='逻辑删除 0-未删除，1-删除'),
    sa.Column('modified_uid', sa.String(length=50), nullable=True, comment='更新人uid'),
    sa.Column('create_uid', sa.String(length=50), nullable=True, comment='创建人uid'),
    sa.Column('modified_uname', sa.String(length=255), nullable=True, comment='更新人昵称'),
    sa.Column('create_uname', sa.String(length=255), nullable=True, comment='创建人昵称'),
    sa.Column('type', sa.Integer(), nullable=True, comment='规格属性的类型；0->规格；1->参数'),
    sa.PrimaryKeyConstraint('id'),
    comment='商品规格表'
    )
    op.create_table('t_specification_option',
    sa.Column('id', sa.BIGINT(), nullable=False, comment='规格项主键id'),
    sa.Column('name', sa.String(length=50), nullable=True, comment='规格项名称'),
    sa.Column('rel_spec_id', sa.BIGINT(), nullable=True, comment='规格id'),
    sa.Column('gmt_create', sa.BIGINT(), nullable=True, comment='创建时间'),
    sa.Column('gmt_modified', sa.BIGINT(), nullable=True, comment='更新时间'),
    sa.Column('enabled', sa.Integer(), nullable=True, comment='逻辑删除 0-未删除，1-删除'),
    sa.Column('modified_uid', sa.String(length=50), nullable=True, comment='更新人uid'),
    sa.Column('create_uid', sa.String(length=50), nullable=True, comment='创建人uid'),
    sa.Column('modified_uname', sa.String(length=255), nullable=True, comment='更新人昵称'),
    sa.Column('create_uname', sa.String(length=255), nullable=True, comment='创建人昵称'),
    sa.PrimaryKeyConstraint('id'),
    comment='规格项'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_specification_option')
    op.drop_table('t_specification')
    op.drop_table('t_spec_type')
    op.drop_table('t_product_full_reduction')
    # ### end Alembic commands ###
