"""empty message

Revision ID: d5f7d2b954b9
Revises: faa41d6d22a1
Create Date: 2024-04-20 19:39:05.429471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5f7d2b954b9'
down_revision = 'faa41d6d22a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_sku_stock',
    sa.Column('id', sa.BIGINT(), nullable=False, comment='SKU主键id'),
    sa.Column('sku_no', sa.String(length=255), nullable=True, comment='SKU编号'),
    sa.Column('rel_product_id', sa.BIGINT(), nullable=True, comment='商品id'),
    sa.Column('title', sa.String(length=255), nullable=True, comment='商品标题'),
    sa.Column('sell_point', sa.String(length=255), nullable=True, comment='卖点'),
    sa.Column('price', sa.Float(), nullable=True, comment='商品价格'),
    sa.Column('num', sa.Integer(), nullable=True, comment='库存数量'),
    sa.Column('lock_stock_num', sa.Integer(), nullable=True, comment='冻结库存数量'),
    sa.Column('version', sa.Integer(), nullable=True, comment='库存版本'),
    sa.Column('image', sa.String(length=512), nullable=True, comment='商品照片'),
    sa.Column('spec_hash', sa.String(length=255), nullable=True, comment='规格哈希值'),
    sa.Column('spec', sa.String(length=255), nullable=True, comment='规格集合'),
    sa.Column('option_ids', sa.String(length=255), nullable=True, comment='规格选项id集合'),
    sa.Column('gmt_create', sa.BIGINT(), nullable=True, comment='创建时间'),
    sa.Column('gmt_modified', sa.BIGINT(), nullable=True, comment='更新时间'),
    sa.Column('enabled', sa.Integer(), nullable=True, comment='逻辑删除 0-未删除, 1-删除'),
    sa.Column('modified_uid', sa.String(length=50), nullable=True, comment='更新人uid'),
    sa.Column('create_uid', sa.String(length=50), nullable=True, comment='创建人uid'),
    sa.Column('modified_uname', sa.String(length=255), nullable=True, comment='更新人昵称'),
    sa.Column('create_uname', sa.String(length=255), nullable=True, comment='创建人昵称'),
    sa.PrimaryKeyConstraint('id'),
    comment='SKU'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_sku_stock')
    # ### end Alembic commands ###
