"""empty message

Revision ID: e0d598295c5a
Revises: ae2a40f018ed
Create Date: 2024-04-16 16:19:25.003716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0d598295c5a'
down_revision = 'ae2a40f018ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('level', sa.SmallInteger(), nullable=True),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('en', sa.String(length=255), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('category_search', sa.Boolean(), nullable=True),
    sa.Column('taobao_query', sa.SmallInteger(), nullable=True),
    sa.Column('taobao_query_search', sa.Boolean(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('create_time', sa.BigInteger(), nullable=False),
    sa.Column('update_time', sa.BigInteger(), nullable=False),
    sa.Column('creator_uid', sa.String(length=64), nullable=False),
    sa.Column('creator_nickname', sa.String(length=64), nullable=False),
    sa.Column('updater_uid', sa.String(length=64), nullable=False),
    sa.Column('updater_nickname', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('mechant_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='商品分类'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category')
    # ### end Alembic commands ###
