"""empty message

Revision ID: e21618fbefb2
Revises: e0d598295c5a
Create Date: 2024-04-16 16:25:47.320670

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e21618fbefb2'
down_revision = 'e0d598295c5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_category',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('level', sa.SmallInteger(), nullable=True, comment='层级'),
    sa.Column('parent_id', sa.BigInteger(), nullable=True, comment='父ID'),
    sa.Column('name', sa.String(length=255), nullable=True, comment='中文'),
    sa.Column('en', sa.String(length=255), nullable=True, comment='英语'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序，暂未使用'),
    sa.Column('catid', sa.Integer(), nullable=True, comment='类目id，关联pid使用'),
    sa.Column('catid_use', sa.SmallInteger(), nullable=True, comment='是否使用catid查询'),
    sa.Column('query_t', sa.String(length=255), nullable=True, comment='淘宝查询'),
    sa.Column('query_t_use', sa.SmallInteger(), nullable=True, comment='是否使用query'),
    sa.Column('weight', sa.Float(), nullable=True, comment='类目单元配重'),
    sa.Column('status', sa.SmallInteger(), nullable=True, comment='状态'),
    sa.Column('gmt_create', sa.BigInteger(), nullable=False, comment='创建时间'),
    sa.Column('gmt_modified', sa.BigInteger(), nullable=False, comment='更新时间'),
    sa.Column('create_uid', sa.String(length=64), nullable=False, comment='创建人uid'),
    sa.Column('create_uname', sa.String(length=64), nullable=False, comment='创建人昵称'),
    sa.Column('modified_uid', sa.String(length=64), nullable=False, comment='更新人uid'),
    sa.Column('modified_uname', sa.String(length=64), nullable=False, comment='更新人昵称'),
    sa.Column('enabled', sa.SmallInteger(), nullable=False, comment='是否删除:0-未删除;1-删除'),
    sa.Column('merchant_id', sa.String(length=32), nullable=True, comment='商户ID'),
    sa.PrimaryKeyConstraint('id'),
    comment='商品分类表'
    )
    op.drop_table('category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('level', mysql.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('parent_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('en', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('sort', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('category_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('category_search', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('taobao_query', mysql.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('taobao_query_search', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('weight', mysql.FLOAT(), nullable=True),
    sa.Column('status', mysql.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('create_time', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('update_time', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('creator_uid', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('creator_nickname', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('updater_uid', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('updater_nickname', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('enabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('mechant_id', mysql.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='商品分类',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='商品分类',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('t_category')
    # ### end Alembic commands ###
