"""empty message

Revision ID: faa41d6d22a1
Revises: dffcc843529a
Create Date: 2024-04-17 23:03:48.104555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faa41d6d22a1'
down_revision = 'dffcc843529a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_cms_subject',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('subject_category_id', sa.BigInteger(), nullable=True, comment='专题分类id'),
    sa.Column('title', sa.String(length=100), nullable=True, comment='专题标题'),
    sa.Column('pic', sa.String(length=500), nullable=True, comment='专题主图'),
    sa.Column('product_count', sa.Integer(), nullable=True, comment='关联产品数量'),
    sa.Column('recommend_status', sa.Integer(), nullable=True, comment='推荐状态'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('collect_count', sa.Integer(), nullable=True),
    sa.Column('read_count', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('album_pics', sa.Text(), nullable=True, comment='画册图片用逗号分割'),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('show_status', sa.Integer(), nullable=True, comment='显示状态：0->不显示；1->显示'),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('forward_count', sa.Integer(), nullable=True, comment='转发数'),
    sa.Column('hot_words', sa.String(length=500), nullable=True, comment='专题热词,聚类出频率最高的前10个词,逗号分割'),
    sa.Column('gmt_create', sa.BigInteger(), nullable=False, comment='创建时间'),
    sa.Column('gmt_modified', sa.BigInteger(), nullable=False, comment='更新时间'),
    sa.Column('create_uid', sa.String(length=64), nullable=False, comment='创建人uid'),
    sa.Column('create_uname', sa.String(length=64), nullable=False, comment='创建人昵称'),
    sa.Column('modified_uid', sa.String(length=64), nullable=False, comment='更新人uid'),
    sa.Column('modified_uname', sa.String(length=64), nullable=False, comment='更新人昵称'),
    sa.Column('enable', sa.SmallInteger(), nullable=False, comment='是否删除:0-未删除;1-删除'),
    sa.Column('merchant_id', sa.Integer(), nullable=True, comment='商户ID'),
    sa.PrimaryKeyConstraint('id'),
    comment='专题表'
    )
    op.create_table('t_cms_subject_category',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('icon', sa.String(length=500), nullable=True, comment='分类图标'),
    sa.Column('subject_count', sa.Integer(), nullable=True, comment='专题数量'),
    sa.Column('show_status', sa.Integer(), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.Column('gmt_create', sa.BigInteger(), nullable=False, comment='创建时间'),
    sa.Column('gmt_modified', sa.BigInteger(), nullable=False, comment='更新时间'),
    sa.Column('create_uid', sa.String(length=64), nullable=False, comment='创建人uid'),
    sa.Column('create_uname', sa.String(length=64), nullable=False, comment='创建人昵称'),
    sa.Column('modified_uid', sa.String(length=64), nullable=False, comment='更新人uid'),
    sa.Column('modified_uname', sa.String(length=64), nullable=False, comment='更新人昵称'),
    sa.Column('enable', sa.SmallInteger(), nullable=False, comment='是否删除:0-未删除;1-删除'),
    sa.Column('merchant_id', sa.Integer(), nullable=True, comment='商户ID'),
    sa.PrimaryKeyConstraint('id'),
    comment='专题分类表'
    )
    op.create_table('t_cms_subject_product_relation',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('subject_id', sa.BigInteger(), nullable=True),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='专题商品关系表'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_cms_subject_product_relation')
    op.drop_table('t_cms_subject_category')
    op.drop_table('t_cms_subject')
    # ### end Alembic commands ###
